In [1]:
#1. Import the numpy package under the name np
import numpy as np


In [2]:
#2. Print the numpy version and the configuration

print(np.__version__)
np.show_config()

1.16.5
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/bharat/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/bharat/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/bharat/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\l

In [3]:
#3. Create a null vector of size 10

Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [16]:
#4. How to find the memory size of any array

Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


In [19]:
(Z.size * Z.itemsize)

800

In [5]:
#5. How to get the documentation of the numpy add function from the command line?
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [6]:
#7. Create a vector with values ranging from 10 to 49

Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [7]:
#8. Reverse a vector (first element becomes last) (★☆☆)

Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [8]:
#Create a 3x3 matrix with values ranging from 0 to 8
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [20]:
#10. Find indices of non-zero elements from [1,2,0,0,4,0]
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [21]:
#11. Create a 3x3 identity matrix 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
#12. Create a 3x3x3 array with random values 

np.random.random((3,3,3)) #u can alter the no of rows and column by adding any no of rowsa in bracket 

array([[[[[0.00228147, 0.15235888],
          [0.79394586, 0.75424857]],

         [[0.88029362, 0.99481618],
          [0.4641546 , 0.72991718]],

         [[0.23664517, 0.78215956],
          [0.94231229, 0.69590529]]],


        [[[0.77355488, 0.63307233],
          [0.03381768, 0.39695135]],

         [[0.05140383, 0.94678539],
          [0.7197033 , 0.30233114]],

         [[0.97150046, 0.08238137],
          [0.98743177, 0.30556611]]],


        [[[0.85728327, 0.8593943 ],
          [0.2863572 , 0.77321703]],

         [[0.81317613, 0.66542559],
          [0.02765539, 0.35173318]],

         [[0.25503766, 0.03121166],
          [0.03418962, 0.66819323]]]],



       [[[[0.53790021, 0.10480942],
          [0.18943962, 0.85263247]],

         [[0.64333114, 0.16517297],
          [0.92728101, 0.20883125]],

         [[0.27455568, 0.66443367],
          [0.6749579 , 0.14670206]]],


        [[[0.86590839, 0.49048763],
          [0.70424386, 0.21625385]],

         [[0.42351252, 0.537

In [64]:
#13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)¶
z=np.random.random((10,10))
print(z.min())
print(z.max())

1.4229319615477465e-05
0.993840855253565


In [69]:
#14. Create a random vector of size 30 and find the mean value (★☆☆)¶
z=np.random.random(30)
z.mean()

0.45773309619035885

In [88]:
#15. Create a 2d array with 1 on the border and 0 inside (★☆☆)¶
z=np.ones((10,10))
z[1:-1,1:-1]=0
z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [96]:
#16. How to add a border (filled with 0's) around an existing array? (★☆☆)¶
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [98]:
#17. What is the result of the following expression? (★☆☆)¶

print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [103]:
z=np.arange(10)
z.reshape(-1,1)


array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [111]:
#18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)¶

Z = np.diag(1+np.arange(4),k=(-1))
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [167]:

for _ in range(4):
    Z = np.random.random((4,5,2))
#Z = (Z - np.mean (Z)) / (np.std (Z))
    print(Z)

[[[0.02912875 0.11180292]
  [0.88950808 0.89930162]
  [0.50245507 0.51246124]
  [0.23652729 0.77087505]
  [0.81418768 0.05757943]]

 [[0.96119282 0.70281951]
  [0.99065579 0.45456988]
  [0.04051963 0.99193472]
  [0.99340053 0.70085349]
  [0.54653359 0.45326712]]

 [[0.01007362 0.68924904]
  [0.91423927 0.33623148]
  [0.04985143 0.50436195]
  [0.95085903 0.62456252]
  [0.76839188 0.54443207]]

 [[0.15113927 0.010112  ]
  [0.86728528 0.21373272]
  [0.05042451 0.85271327]
  [0.86541175 0.05591792]
  [0.45917438 0.33595955]]]
[[[0.85845412 0.05689982]
  [0.03654204 0.17856512]
  [0.04990585 0.54180798]
  [0.45215047 0.477991  ]
  [0.10546991 0.61541302]]

 [[0.62242789 0.0321653 ]
  [0.44946001 0.26894312]
  [0.85789056 0.87930575]
  [0.76421489 0.46127408]
  [0.86497571 0.281944  ]]

 [[0.03642477 0.62307071]
  [0.81072294 0.0535599 ]
  [0.33114926 0.92467019]
  [0.74208311 0.24132835]
  [0.35792249 0.8776509 ]]

 [[0.26786297 0.94338899]
  [0.47119612 0.02391986]
  [0.22588921 0.86873698

In [162]:
from random import seed
from random import randint
# seed random number generator
#seed(1)
# generate some integers
for _ in range(10):
	value = randint(1, 10)
	print(value)

9
4
1
4
9
9
4
7
9
6


In [181]:
#30. How to find common values between two arrays? (★☆☆)¶

Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[1 2 7]
