In [ ]:
#supervised:historical/batch data is available
#also known as predictive modeling
#we  save the model by suing pickle in python
#in ml librabry sklearn(joblib) ,keras,pytorch
#
#interview quetion:how many haperparameter ue in linear regression
#
#
#

In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

C:\Users\bharat\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\bharat\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [4]:
DF=pd.DataFrame({"Area":[2600,3300,2500,3000,4500],
                 "BHK":[3,4,3,None,5],
                "H_Age":[5,10,1,3,6],
                "R_price":[550000,610000,590000,720000,780000]})

In [5]:
DF

Area  BHK  H_Age  R_price
0  2600  3.0      5   550000
1  3300  4.0     10   610000
2  2500  3.0      1   590000
3  3000  NaN      3   720000
4  4500  5.0      6   780000

In [6]:
DF.BHK.median()

3.5

In [7]:
import math 

In [8]:
median_bedroom = math.floor(DF.BHK.median())

In [9]:
median_bedroom

3

In [10]:
DF['BHK']=DF['BHK'].fillna(median_bedroom)
DF

Area  BHK  H_Age  R_price
0  2600  3.0      5   550000
1  3300  4.0     10   610000
2  2500  3.0      1   590000
3  3000  3.0      3   720000
4  4500  5.0      6   780000

In [16]:
reg = LinearRegression()

In [18]:
reg.fit(DF[['Area', 'BHK', 'H_Age']], DF.R_price)      #fit :x bar,ybar and m=,y=mx+c


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [19]:
reg.coef_                            #value of m1,m2,m3

array([    278.34868887, -159744.86180014,   -5294.11764706])

In [22]:
reg.intercept_                               #value of c (constant)

366403.2600992203

In [23]:
reg.predict([[3000,4,0]])

array([562469.87951807])

In [24]:
import pickle

In [26]:
with open('model_pickle','wb') as f:                #run only once it creates a file for saving as name modelpickle
    pickle.dump(reg,f)                                3

In [27]:
with open('model_pickle','rb') as f:                #run only once it creates a file for saving as name modelpickle
    mp=pickle.load(f)

In [28]:
mp.predict([[3500,4,7]])

array([664585.40042523])

In [29]:
from sklearn.externals import joblib

In [30]:
joblib.dump(reg, 'model_joblib')

['model_joblib']

In [31]:
mj = joblib.load('model_joblib')

In [32]:
mj.predict([[3500, 4, 7]])

array([664585.40042523])

In [ ]:
#################Rough work######################################

In [33]:
AA=pd.read_csv("Desktop/data.csv")

In [34]:
AA

Area  BHK  Age
0  1300    2    3
1  3400    4    1
2  2000    3    0

In [35]:
mj.predict(AA)

array([392884.47909284, 668515.23742027, 443866.05244507])