In [2]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [6]:
AA=pd.read_csv("sample1.csv")

In [7]:
AA

Unnamed: 0  age  milage  seater   price
0           0    0      19       5  900000
1           1    4      15       2  700000
2           2    8      14       8  600000
3           3   12      16       7  400000

In [8]:
AA.drop(['Unnamed: 0'],axis=1)

age  milage  seater   price
0    0      19       5  900000
1    4      15       2  700000
2    8      14       8  600000
3   12      16       7  400000

In [14]:
reg=LinearRegression()

In [15]:
reg.fit(AA[['age', 'milage', 'seater']], AA.price)  

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [16]:
reg.coef_

array([-44791.66666667,  -4166.66666667,  12500.        ])

In [17]:
reg.intercept_

916666.6666666667

In [18]:
reg.predict([[3,20,4]])

array([748958.33333333])

In [21]:
reg.predict([[4,22,8]])

array([745833.33333333])